#!/usr/bin/env bash
# add_app_to_nginx.sh — Write an Nginx server block for a deployed app.
# Usage: ./add_app_to_nginx.sh --app-id <id> --port <internal_port> --domain <domain> [--apply]
set -euo pipefail

APP_ID=""
PORT=""
DOMAIN=""
APPLY=false
GITDEPLOY_D="/etc/nginx/gitdeploy.d"

usage() {
  echo "Usage: $0 --app-id <id> --port <port> --domain <domain> [--apply]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --app-id)  APP_ID="$2"; shift 2 ;;
    --port)    PORT="$2"; shift 2 ;;
    --domain)  DOMAIN="$2"; shift 2 ;;
    --apply)   APPLY=true; shift ;;
    *) usage ;;
  esac
done

[[ -z "$APP_ID" || -z "$PORT" || -z "$DOMAIN" ]] && usage

SUBDOMAIN="app-${APP_ID}.${DOMAIN}"
CONF_FILE="${GITDEPLOY_D}/app-${APP_ID}.conf"

echo "==> Writing Nginx block for ${SUBDOMAIN} -> 127.0.0.1:${PORT}"

sudo mkdir -p "$GITDEPLOY_D"

sudo tee "$CONF_FILE" > /dev/null <<EOF
# App ${APP_ID} — ${SUBDOMAIN}
# Generated by add_app_to_nginx.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
server {
    listen 80;
    server_name ${SUBDOMAIN};

    location / {
        proxy_pass         http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

    # Health check endpoint
    location /health {
        access_log off;
        proxy_pass http://127.0.0.1:${PORT}/health;
    }
}
EOF

echo "==> Config written to ${CONF_FILE}"

if $APPLY; then
  echo "==> Testing Nginx config..."
  sudo nginx -t
  echo "==> Reloading Nginx..."
  sudo nginx -s reload
  echo "==> Done. App ${APP_ID} is now accessible at http://${SUBDOMAIN}"
else
  echo "==> Dry run complete. Run 'sudo nginx -s reload' to apply."
  echo "==> App ${APP_ID} will be accessible at http://${SUBDOMAIN}"
fi
