#!/usr/bin/env python3
"""
generate_nginx_conf.py — Generate Nginx config blocks for all gitDeploy apps.

Reads app data from the gitDeploy database and writes individual Nginx config
files for every RUNNING app.

Usage:
  python3 scripts/generate_nginx_conf.py --domain yourdomain.com [--dry-run]

Requirements:
  pip install sqlalchemy aiosqlite
"""
import argparse
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

TEMPLATE = """# App {app_id} — {subdomain}.{domain}
# Generated by generate_nginx_conf.py
server {{
    listen 80;
    server_name {subdomain}.{domain};

    location / {{
        proxy_pass         http://127.0.0.1:{internal_port};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }}
}}
"""


async def main(domain: str, dry_run: bool, output_dir: str) -> None:
    from sqlalchemy import select
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
    from app.config import Config
    from app.database import ASYNC_DATABASE_URL
    from app.models.app_model import AppModel
    from app.constants import AppStatus

    engine = create_async_engine(ASYNC_DATABASE_URL)
    Session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    async with Session() as db:
        result = await db.execute(
            select(AppModel).where(
                AppModel.status == AppStatus.RUNNING,
                AppModel.internal_port.isnot(None),
            )
        )
        apps = result.scalars().all()

    await engine.dispose()

    if not apps:
        print("No RUNNING apps found in the database.")
        return

    generated = 0
    for app in apps:
        conf_content = TEMPLATE.format(
            app_id=app.id,
            subdomain=app.subdomain,
            domain=domain,
            internal_port=app.internal_port,
        )
        conf_file = out_path / f"app-{app.id}.conf"
        if dry_run:
            print(f"--- Would write: {conf_file} ---")
            print(conf_content)
        else:
            conf_file.write_text(conf_content)
            print(f"Written: {conf_file}")
        generated += 1

    print(f"\nGenerated {generated} Nginx config(s) in {out_path}")
    if not dry_run:
        print("Run 'sudo nginx -s reload' to apply.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Nginx configs for gitDeploy apps")
    parser.add_argument("--domain", required=True, help="Base domain (e.g. yourdomain.com)")
    parser.add_argument("--dry-run", action="store_true", help="Print configs without writing files")
    parser.add_argument("--output-dir", default="/etc/nginx/gitdeploy.d", help="Output directory for config files")
    args = parser.parse_args()

    asyncio.run(main(args.domain, args.dry_run, args.output_dir))
