#!/usr/bin/env bash
# setup_cloudflare_tunnel.sh — Write a cloudflared config for gitDeploy.
#
# IMPORTANT: This script only writes configuration files.
# It does NOT start the tunnel or modify any Cloudflare DNS records automatically.
# You must run 'cloudflared tunnel run gitdeploy' manually after reviewing the config.
#
# Prerequisites:
#   - cloudflared installed: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/
#   - A tunnel already created: cloudflared tunnel create gitdeploy
#   - Tunnel credentials JSON must exist at ~/.cloudflared/<TUNNEL_ID>.json
#
# Usage:
#   ./setup_cloudflare_tunnel.sh --tunnel-id <id> --domain <domain> [--config-dir <dir>]
set -euo pipefail

TUNNEL_ID=""
DOMAIN=""
CONFIG_DIR="${HOME}/.cloudflared"
TUNNEL_NAME="gitdeploy"

usage() {
  echo "Usage: $0 --tunnel-id <tunnel-uuid> --domain <domain> [--config-dir <dir>]"
  echo ""
  echo "Options:"
  echo "  --tunnel-id    UUID of the Cloudflare tunnel (from: cloudflared tunnel list)"
  echo "  --domain       Base domain (e.g. yourdomain.com)"
  echo "  --config-dir   Where to write the config (default: ~/.cloudflared)"
  echo ""
  echo "Steps after running this script:"
  echo "  1. Review: ${CONFIG_DIR}/config.yml"
  echo "  2. Add DNS CNAME records (see output below)"
  echo "  3. Start tunnel: cloudflared tunnel run ${TUNNEL_NAME}"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --tunnel-id)   TUNNEL_ID="$2"; shift 2 ;;
    --domain)      DOMAIN="$2"; shift 2 ;;
    --config-dir)  CONFIG_DIR="$2"; shift 2 ;;
    *) usage ;;
  esac
done

[[ -z "$TUNNEL_ID" || -z "$DOMAIN" ]] && usage

CREDENTIALS_FILE="${CONFIG_DIR}/${TUNNEL_ID}.json"
CONFIG_FILE="${CONFIG_DIR}/config.yml"

if [[ ! -f "$CREDENTIALS_FILE" ]]; then
  echo "ERROR: Tunnel credentials not found at ${CREDENTIALS_FILE}"
  echo "       Create the tunnel first: cloudflared tunnel create ${TUNNEL_NAME}"
  exit 1
fi

mkdir -p "$CONFIG_DIR"

echo "==> Writing Cloudflare Tunnel config to ${CONFIG_FILE}"

cat > "$CONFIG_FILE" <<EOF
# Cloudflare Tunnel configuration for gitDeploy
# Tunnel ID: ${TUNNEL_ID}
# Domain: ${DOMAIN}
# Generated by setup_cloudflare_tunnel.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# IMPORTANT: This file only configures routing.
# DNS CNAME records must be created manually in Cloudflare Dashboard
# or via: cloudflared tunnel route dns ${TUNNEL_NAME} '*.${DOMAIN}'
#
# To start the tunnel: cloudflared tunnel run ${TUNNEL_NAME}

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDENTIALS_FILE}

ingress:
  # gitDeploy API
  - hostname: api.${DOMAIN}
    service: http://localhost:8000

  # gitDeploy UI
  - hostname: ${DOMAIN}
    service: http://localhost:5173

  # Wildcard: individual deployed apps (app-1.domain.com, app-2.domain.com, ...)
  # Nginx handles the routing from *.domain.com to the correct internal port
  - hostname: "*.${DOMAIN}"
    service: http://localhost:80

  # Catch-all (required by cloudflared)
  - service: http_status:404
EOF

echo "==> Config written to ${CONFIG_FILE}"
echo ""
echo "=========================================="
echo "  NEXT STEPS (manual)"
echo "=========================================="
echo ""
echo "1. Add DNS CNAME records in Cloudflare Dashboard:"
echo "   Type: CNAME  Name: api      Target: ${TUNNEL_ID}.cfargotunnel.com"
echo "   Type: CNAME  Name: @        Target: ${TUNNEL_ID}.cfargotunnel.com"
echo "   Type: CNAME  Name: *        Target: ${TUNNEL_ID}.cfargotunnel.com"
echo ""
echo "   Or via CLI (requires cloudflared to be logged in):"
echo "   cloudflared tunnel route dns ${TUNNEL_NAME} api.${DOMAIN}"
echo "   cloudflared tunnel route dns ${TUNNEL_NAME} ${DOMAIN}"
echo "   cloudflared tunnel route dns ${TUNNEL_NAME} '*.${DOMAIN}'"
echo ""
echo "2. Review the config: cat ${CONFIG_FILE}"
echo ""
echo "3. Start the tunnel:"
echo "   cloudflared tunnel run ${TUNNEL_NAME}"
echo ""
echo "4. To run as a service (Linux):"
echo "   sudo cloudflared service install"
echo "   sudo systemctl start cloudflared"
echo ""
echo "=========================================="
