#!/usr/bin/env bash
# setup_nginx.sh — Configure Nginx master vhost for gitDeploy subdomain routing.
# Usage: ./setup_nginx.sh --domain yourdomain.com [--apply]
# Does NOT restart Nginx unless --apply is passed.
set -euo pipefail

DOMAIN=""
APPLY=false
NGINX_SITES_DIR="/etc/nginx/sites-available"
NGINX_ENABLED_DIR="/etc/nginx/sites-enabled"
CONF_NAME="gitdeploy"

usage() {
  echo "Usage: $0 --domain <domain> [--apply]"
  echo "  --domain   Base domain (e.g. yourdomain.com)"
  echo "  --apply    Reload Nginx after writing config (requires sudo)"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2 ;;
    --apply)  APPLY=true; shift ;;
    *) usage ;;
  esac
done

[[ -z "$DOMAIN" ]] && usage

CONF_FILE="${NGINX_SITES_DIR}/${CONF_NAME}.conf"

echo "==> Writing master Nginx config to ${CONF_FILE}"

sudo mkdir -p "$NGINX_SITES_DIR" "$NGINX_ENABLED_DIR"

sudo tee "$CONF_FILE" > /dev/null <<EOF
# gitDeploy — master wildcard config for *.${DOMAIN}
# Generated by setup_nginx.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Individual app blocks are included from: /etc/nginx/gitdeploy.d/

# Include per-app blocks
include /etc/nginx/gitdeploy.d/*.conf;
EOF

# Create per-app include directory
sudo mkdir -p /etc/nginx/gitdeploy.d

# Enable the site
sudo ln -sf "$CONF_FILE" "${NGINX_ENABLED_DIR}/${CONF_NAME}.conf"

echo "==> Master config written."
echo "==> Per-app configs go in: /etc/nginx/gitdeploy.d/"

if $APPLY; then
  echo "==> Testing Nginx config..."
  sudo nginx -t
  echo "==> Reloading Nginx..."
  sudo nginx -s reload
  echo "==> Nginx reloaded."
else
  echo "==> Dry run complete. Run 'sudo nginx -s reload' to apply."
fi
