from app.Errors.app_errors import (
    AppBaseError,
    InvalidRepoURLError,
    MalformedRepoURLError,
    UnexpectedRepoURLFormatError,
    GitHubAPIConnectionError,
    RepoNotFoundOrPrivateError,
    GitHubAPIError,
    PrivateRepoNotSupportedError,
    GitCloneError,
    GitPullError,
    DockerfileNotFoundError,
    DockerImageRemovalError,
    DockerBuildError,
    DockerImageNotFoundError,
    DockerContainerRemovalError,
    DockerRunError,
    AppNotFoundError,
    AppCreationError,
    DeployGitPermissionDeniedError,
    DeployGitValidationError,
    DeployDockerBuildError,
    DeployDockerRunError,
    DatabaseConnectionError,
    InternalServerError,
)

from app.Errors.error_logger import log_error